
version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_ttl256
    restart: always
    environment:
      POSTGRES_DB: engcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      HIKARI_CONNECTION_TIMEOUT: 40000
      HIKARI_MAXIMUM_POOL_SIZE: 250
      HIKARI_MINIMUM_IDLE: 20
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    image: minio/minio:latest
    container_name: minio_server_ttl256
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "sF021A-?=sZz"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
     - mynetwork
  app:
    build:
      context: ./
      dockerfile: infra/Dockerfile
    container_name: seletivo_ttl256
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/engcomp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: 'sF021A-?=sZz'
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  nginx:
    image: nginx:1.26-alpine
    container_name: nginx_ttl256
    ports:
      - "9003:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    restart: always
    networks:
      - mynetwork
volumes:
  postgres_data:
  minio_data:
networks:
  mynetwork:
    driver: bridge
